server:
  port: 8888
spring:
  application:
    name: tesla
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dariobritos/proygrad-config.git

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.proygrad: 'DEBUG'